
server:
  port: 0
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: devday-bucket
    credentials:
      access-key: AKIAXEUXRPXDUUVY2A5E
      secret-key: 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
    stack:
      auto: false
spring:
  application:
    name: challenge-service
  datasource:
      url: jdbc:mysql://j8c209.p.ssafy.io:3307/devday?useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      username: root
      password: devday1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    
    database : mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  

logging:
  level:
    com.example.challengeservice.client: DEBUG

