server:
  port: 8003

spring:
  application:
    name: pay-service
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:pay-service
#    username: sa
#    password: 1234
  datasource:
    url: jdbc:mysql://localhost:3309/devday?useSSL=false&serverTimezone=UTC
    username: root
    password: devday1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true


eureka:
  instance:
    instance-id: ${spring.application.name}:${spirng.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


payment:
  toss:
    baseUrl: https://api.tosspayments.com
    secret: dGVzdF9za19qa1lHNTdFYmEzR1JCWGcxbUs2OHBXRE94bUExOg==
    path:
      confirm: /v1/payments/confirm
      cancel: /v1/payments/%s/cancel

openapi:
  nonghyup:
    baseUrl: https://developers.nonghyup.com
    accessToken: 1bde7fbe896bd899b734984345141a21a4acb8e6b20fe3f22517d21bc5fdbda2
    iscd: '001780'
    fintechApsno: '001' # 테스트
    apiSvcCd: ReceivedTransferA
    otlt: Devday 상금


logging:
  level:
    com.example.payservice: debug